import React, { type ReactNode } from 'react';
import { useConnectionEffect } from 'wagmi';
import type { Chain } from 'wagmi/chains';
import { useIsMounted } from './useIsMounted';
import { cssStringFromTheme } from '../../css/cssStringFromTheme';
import type { ThemeVars } from '../../css/sprinkles.css';
import type { Locale } from '../../locales';
import { lightTheme } from '../../themes/lightTheme';
import { TransactionStoreProvider } from '../../transactions/TransactionStoreContext';
import { composeProviders } from './composeProviders';
import { I18nProvider } from './I18nContext';
import { ModalProvider } from './ModalContext';
import {
  ModalSizeOptions,
  ModalSizeProvider,
  type ModalSizes,
} from './ModalSizeContext';
import {
  type AppInfo,
  type AvatarComponent,
  type DisclaimerComponent,
  type RainbowKitConfig,
  RainbowKitConfigContext,
  defaultAppInfo,
  useThemeId,
} from './RainbowKitConfigContext';
import { RainbowKitChainProvider } from './RainbowKitChainContext';
import { ShowBalanceProvider } from './ShowBalanceContext';
import { WalletButtonProvider } from './WalletButtonContext';
import { usePreloadImages } from './usePreloadImages';
import { clearWalletConnectDeepLink } from './walletConnectDeepLink';
import { EmojiAvatar } from '../Avatar/EmojiAvatar';

export type {
  DisclaimerComponent,
  AvatarComponent,
} from './RainbowKitConfigContext';

const attr = 'data-sk';

const createThemeRootProps = (id: string | undefined) => ({ [attr]: id || '' });

const createThemeRootSelector = (id: string | undefined) => {
  if (id && !/^[a-zA-Z0-9_]+$/.test(id)) {
    throw new Error(`Invalid ID: ${id}`);
  }

  return id ? `[${attr}="${id}"]` : `[${attr}]`;
};

export const useThemeRootProps = () => createThemeRootProps(useThemeId());

export type Theme =
  | ThemeVars
  | {
      lightMode: ThemeVars;
      darkMode: ThemeVars;
    };

export interface RainbowKitProviderProps {
  initialChain?: Chain | number;
  id?: string;
  children: ReactNode;
  theme?: Theme | null;
  showRecentTransactions?: boolean;
  appInfo?: AppInfo;
  avatar?: AvatarComponent;
  modalSize?: ModalSizes;
  locale?: Locale;
}

const defaultTheme = lightTheme();

export function RainbowKitProvider({
  appInfo,
  avatar,
  children,
  id,
  initialChain,
  locale,
  modalSize = ModalSizeOptions.WIDE,
  showRecentTransactions = false,
  theme = defaultTheme,
}: RainbowKitProviderProps) {
  // Defer wagmi-dependent side effects (wallet icon preload + WC deep-link
  // clearing on disconnect) until after the first client render. Calling
  // these during SSR throws WagmiProviderNotFoundError because the
  // WagmiProvider Config context isn't populated on the server.
  const mounted = useIsMounted();

  if (typeof theme === 'function') {
    throw new Error(
      'A theme function was provided to the "theme" prop instead of a theme object. You must execute this function to get the resulting theme object.',
    );
  }

  const selector = createThemeRootSelector(id);

  const config: RainbowKitConfig = {
    appInfo: { ...defaultAppInfo, ...appInfo },
    avatar: avatar ?? EmojiAvatar,
    showRecentTransactions,
    themeId: id,
  };

  // Provider order matters: ModalSizeProvider reads WalletButtonContext;
  // TransactionStoreProvider reads from RainbowKitChainProvider; etc. Don't
  // reorder without verifying the inner providers' useContext dependencies.
  const providers = [
    [RainbowKitChainProvider, { initialChain }],
    [WalletButtonProvider, {}],
    [I18nProvider, { locale }],
    [ModalSizeProvider, { modalSize }],
    [TransactionStoreProvider, {}],
    [RainbowKitConfigContext.Provider, { value: config }],
    [ShowBalanceProvider, {}],
    [ModalProvider, {}],
  ] as const;

  const themedChildren = theme ? (
    <div {...createThemeRootProps(id)}>
      <style
        // biome-ignore lint/security/noDangerouslySetInnerHtml: TODO
        dangerouslySetInnerHTML={{
          // Selectors are sanitized to only contain alphanumeric
          // and underscore characters. Theme values generated by
          // cssStringFromTheme are sanitized, removing
          // characters that terminate values / HTML tags.
          __html: [
            `${selector}{${cssStringFromTheme(
              'lightMode' in theme ? theme.lightMode : theme,
            )}}`,

            'darkMode' in theme
              ? `@media(prefers-color-scheme:dark){${selector}{${cssStringFromTheme(
                  theme.darkMode,
                  { extends: theme.lightMode },
                )}}}`
              : null,
          ].join(''),
        }}
      />
      {children}
    </div>
  ) : (
    children
  );

  return (
    <>
      {mounted && <WagmiEffects />}
      {composeProviders(providers, themedChildren)}
    </>
  );
}

/**
 * Isolates the two wagmi-hook calls (icon preload + WC deep-link clear on
 * disconnect) so that they only run after the provider has mounted on the
 * client. Rendering this during SSR would throw WagmiProviderNotFoundError.
 */
function WagmiEffects() {
  usePreloadImages();
  useConnectionEffect({ onDisconnect: clearWalletConnectDeepLink });
  return null;
}
